### ISSUE TITLE
AccessViolationException with prerelease 2.4.0-unstable0038

### ISSUE THREAD

**Issue by gitfool** [GitTools/GitLink#103]
We're getting an AccessViolationException using the latest GitLink prerelease (2.4.0-unstable0038).

See the following extract from our TeamCity Cake build:
```
[11:49:24]W:	 [Step 2/2] Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[11:49:24]W:	 [Step 2/2]    at System.String.TrimHelper(Int32 trimType)
[11:49:24]W:	 [Step 2/2]    at Catel.Argument.IsNotNullOrWhitespace(String paramName, String paramValue) in C:\CI_WS\Ws\84541\Source\Catel\src\Catel.Core\Catel.Core.Shared\Argument.cs:line 129
[11:49:24]W:	 [Step 2/2]    at GitLink.ProjectExtensions.CreateSrcSrv(Project project, String srcsrvFile, SrcSrvContext srcSrvContext) in C:\CI_WS\Ws\96208\Source\GitLink\src\GitLink\Extensions\ProjectExtensions.cs:line 0
[11:49:24]W:	 [Step 2/2]    at GitLink.Linker.LinkProject(Context context, Project project, String pdbStrFile, String shaHash, String pathPdbDirectory) in C:\CI_WS\Ws\96208\Source\GitLink\src\GitLink\Linker.cs:line 236
[11:49:24]W:	 [Step 2/2]    at GitLink.Linker.Link(Context context) in C:\CI_WS\Ws\96208\Source\GitLink\src\GitLink\Linker.cs:line 110
[11:49:24]W:	 [Step 2/2]    at GitLink.Program.Main(String[] args) in C:\CI_WS\Ws\96208\Source\GitLink\src\GitLink\Program.cs:line 46

[11:49:25]W:	 [Step 2/2] An error occured when executing task 'NuGet-Package'.
[11:49:25]W:	 [Step 2/2] Error: Cake.Core.CakeException: GitLink: Process returned an error (exit code 255).
[11:49:25]W:	 [Step 2/2]    at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
[11:49:25]W:	 [Step 2/2]    at Cake.Common.Tools.GitLink.GitLinkRunner.Run(DirectoryPath repositoryRootPath, GitLinkSettings settings)
[11:49:25]W:	 [Step 2/2]    at Cake.Common.Tools.GitLink.GitLinkAliases.GitLink(ICakeContext context, DirectoryPath repositoryRootPath, GitLinkSettings settings)
[11:49:25]W:	 [Step 2/2]    at Submission#0.GitLink(DirectoryPath repositoryRootPath, GitLinkSettings settings)
[11:49:25]W:	 [Step 2/2]    at Submission#0.<.ctor>b__459_18()
[11:49:25]W:	 [Step 2/2]    at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass4_0.<Does>b__0(ICakeContext context)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.ActionTask.Execute(ICakeContext context)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
[11:49:25]W:	 [Step 2/2]    at Cake.Scripting.BuildScriptHost.RunTarget(String target)
[11:49:25]W:	 [Step 2/2]    at Submission#0..ctor(Object[] submissionArray, Object& submissionResult)
[11:49:25]W:	 [Step 2/2]    at Submission#0.<Factory>(Object[] submissionArray)
[11:49:25]W:	 [Step 2/2]    at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmission(Func`2 submissionRunner)
[11:49:25]W:	 [Step 2/2]    at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
[11:49:25]W:	 [Step 2/2]    at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
[11:49:25]W:	 [Step 2/2]    at Microsoft.CodeAnalysis.Scripting.CSharp.CSharpScript.Eval(String code, ScriptOptions options, Object globals)
[11:49:25]W:	 [Step 2/2]    at Cake.Scripting.Roslyn.Nightly.DefaultRoslynNightlyScriptSession.Execute(Script script)
[11:49:25]W:	 [Step 2/2]    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
[11:49:25]W:	 [Step 2/2]    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
[11:49:25]W:	 [Step 2/2]    at Cake.CakeApplication.Run(CakeOptions options)
[11:49:25]W:	 [Step 2/2]    at Cake.Program.Main()
[11:49:25]W:	 [Step 2/2] Process exited with code 1
```
This goes away when we switch to the last GitLink stable release (2.3.0).

**Comment by GeertvanHorrik** [comment]
Hmmmm, will look into this when I have time, thanks for reporting.

**Comment by caioproiete** [comment]
I can reproduce this on my machine, running GitLink agains a newly created project (Visual Studio -> File -> New -> Project -> Class Library) using .NET 4.5.1.

GitLink v1.2.0.0
================

Arguments: C:\caio-proiete\ClassLibraryWithGitLink -u https://myvcs.com/projects/XXX/repos/repo/name/browse/{filename}?at={revision}&raw -f ClassLibraryWithGitLink.sln

Extracting embedded pdbstr.exe
Using provider 'CustomUrlProvider'
No sha hash is available on the context, retrieving latest commit of current branch
Using commit sha 'c094da3935f369dc69ad3bd94dc837d440fd5deb' as version stamp
Found '1' project(s)

Handling project 'ClassLibraryWithGitLink'
  Verifying pdb file

Unhandled Exception: System.AccessViolationException: Atcaio-proieteted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.String.TrimHelper(Int32 trimType)
   at Catel.Argument.IsNotNullOrWhitespace(String paramName, String paramValue)
in C:\CI_WS\Ws\84541\Source\Catel\src\Catel.Core\Catel.Core.Shared\Argument.cs:line 129
   at GitLink.ProjectExtensions.CreateSrcSrv(Project project, String srcsrvFile, SrcSrvContext srcSrvContext) in C:\caio-proiete\GitLink\src\GitLink
\Extensions\ProjectExtensions.cs:line 44 at GitLink.Linker.LinkProject(Context context, Project project, String pdbStr
File, String shaHash, String pathPdbDirectory) in C:\caio-proiete\GitLink\src\GitLink\Linker.cs:line 236
   at GitLink.Linker.Link(Context context) in C:\caio-proiete\GitLink\src\GitLink\Linker.cs:line 113
   at GitLink.Program.Main(String[] args) in C:\caio-proiete\GitLink\src\GitLink\Program.cs:line 49

**Comment by kzu** [comment]
I can reproduce the error with GitLink 2.4.0-unstable0034 but not with GitLink 2.4.0-unstable0026.

**Comment by GeertvanHorrik** [comment]
Please try Build - 2.4.0-unstable.48

**Comment by caioproiete** [comment]
@GeertvanHorrik: Stupid question: Where can I download unstable builds from?

**Comment by GeertvanHorrik** [comment]
See https://www.nuget.org/packages/gitlink/2.4.0-unstable0052

**Comment by gitfool** [comment]
👍 Prerelease 2.4.0-unstable0052 worked for me.

**Comment by GeertvanHorrik** [comment]
Thanks for the feedback!
