### ISSUE TITLE
VS15 support

### ISSUE THREAD

**Issue by matkoch** [GitTools/GitLink#152]
When calling `gitlink.exe <pdbFile>` it throws an exception:

```
Pdb header didn't match

Unhandled Exception: GitLink.GitLinkException: Pdb header didn't match
   at GitLink.Pdb.PdbFile.CheckPdbHeader()
   at GitLink.Pdb.PdbFile..ctor(String path)
   at GitLink.Linker.Link(String pdbPath, LinkOptions options)
   at GitLink.Program.Main(String[] args)
```

I compiled it with VS2017 with target framework net46. I made sure that pdb and assembly matches by removing *obj*  and *bin* directory first.

*Update:*

Probably related issue is Microsoft/microsoft-pdb#23.

**Comment by matkoch** [comment]
Looks like the fault was on my side. At least if you're aware that BSJB and MPDB are not supported. I was  actually missing:

```
<DebugType>pdbonly</DebugType>
<DebugSymbols>True</DebugSymbols>
```
Maybe it would be helpful to state the possibility of those missing tags in the exception message.
