### ISSUE TITLE
Unable to determine git provider. How to specify the provider?

### ISSUE THREAD

**Issue by amamh** [GitTools/GitLink#78]
I have my own Stash server which I believe is the same as Bitbucket.

I keep getting this error:

> gitlink . -u https://ah87584@cedt-icg-bitbucket.nam.nsroot.net/bitbucket/scm/~ah87584/orleans-dictstreamprovider.git -f DictionaryPersistentStreamProvider.sln

> Cannot determine git provider
An unexpected error occurred | [GitLinkException] GitLink.GitLinkException: Cannot determine git provider
   at GitLink.Context.ValidateContext() in C:\Users\AH87584\Documents\Visual Studio 2013\Projects\GitLink\src\GitLink\Context.cs:line 108
   at GitLink.Linker.Link(Context context) in C:\Users\AH87584\Documents\Visual Studio 2013\Projects\GitLink\src\GitLink\Linker.cs:line 34
   at GitLink.Program.Main(String[] args) in C:\Users\AH87584\Documents\Visual Studio 2013\Projects\GitLink\src\GitLink\Program.cs:line 46

There is no option for me to specify the git provider. How do I tell it to use Bitbucket git provider?

**Comment by amamh** [comment]
duplicate of https://github.com/GitTools/GitLink/issues/66
